[project]
name = "seekdeep"
version = "0.1.0"
description = "A compact implementation of the DeepSearch concept using deepseek-r1 via Ollama"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "chromadb>=0.4.18",
    "requests>=2.28.0",
    "pydantic>=1.10.8",
]
